config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  root to: "home#index"

  resources :posts
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_admin!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_admin!

  def index
  end
end

app/controllers/posts_controller.rb
# :no-doc:
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.order(created_at: :desc)
  end

  def show() end

  def new
    @post = Post.new
  end

  def edit() end

  def create
    post = Post.new(post_params)
    if post.save
      flash[:notice] = 'A new Post is Created'
      redirect_to posts_path
    else
      flash[:alert] = post.errors.full_messages.join(' and ')
      redirect_to new_post_path
    end
  end

  def update
    if @post.update(post_params)
      flash[:notice] = 'Updated the Post'
      redirect_to post_path(@post)
    else
      flash[:alert] = @post.errors.full_messages.join(' and ')
      redirect_to edit_post_path(@post)
    end
  end

  def destroy
    if @post.destroy
      flash[:notice] = 'Post deleted'
    else
      flash[:alert] = @post.errors.full_messages.join(' and ')
    end
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/home/index.html.erb
<% if current_admin %>
  <%= link_to 'Sign Out', destroy_admin_session_path %><br>
  <%= link_to 'Posts', posts_path %>
<% else %>
  <%= link_to 'Admin Login', new_admin_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Multiply</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="container">
  <div class="row margin-left">
    <table>
        <tr>
          <td>Title : </td><td><%= form.text_field :title, class: 'text' %></td>
        </tr>
        <tr>
          <td>Content : </td>
          <td><%= form.text_area :content, cols: 80, rows: 10 %></td>
        </tr>
        <tr>
          <td><%= form.submit 'OK', class: 'btn btn-default' %></td>
          <td><%= link_to 'Home', posts_path, class: 'btn btn-primary' %></td>
        </tr>
    </table>
  </div>
</div>

app/views/posts/edit.html.erb
<h1> Edit Post </h1>
<%= form_for @post do |form| %>
  <%= render 'form', form: form %>
<% end %>

app/views/posts/index.html.erb
<div class="container">
  <%= link_to 'Sign Out', destroy_admin_session_path, method: :delete %>
  <div class="row margin-left">
    <table style="width: 100%" class="table-hover table-striped table-condensed">
      <thead>
        <th>Title</th>
        <th>Content</th>
        <th></th>
        <th></th>
        <th></th>
      </thead>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.title %></td>
          <td><%= truncate post.content %></td>
          <td><%= link_to 'Show', post_path(post) %></td>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Destroy', post_path(post), method: :delete, data: { confirm: "Are you sure?" } %></td>
        </tr>
      <% end %>
    </table>
  </div>
  <%= link_to 'Create Post', new_post_path %>
</div>

app/views/posts/new.html.erb
<h1>Upload New Post</h1>
<%= form_for @post do |form| %>
  <%= render 'form', form: form %>
<% end %>

app/views/posts/show.html.erb
<div class="container">
  <div class="row margin-left">
    <h1><%= @post.title.titleize %></h1>
    <p class="col-sm-10"><%= @post.content %>
  </div>
  <%= link_to 'Home', posts_path, class: 'btn btn-default' %>
  <%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-primary' %>
  <%= link_to 'Destroy', post_path(@post), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger' %>
</div>

app/views/posts/update.html.erb
<h1>Post#update</h1>
<p>Find me in app/views/post/update.html.erb</p>